#!/usr/bin/env node
// Generate the Traditional Chinese (zh-Hant) translations by converting the
// Simplified Chinese (zh) content with OpenCC (Simplified → Traditional, Taiwan
// standard, character-level). Simplified `zh` stays the source of truth; the
// derived `zh-Hant` blocks are regenerated by this script — re-run it whenever
// the Simplified strings change so the two scripts stay in sync.
//
// It converts string VALUES only. Object keys (i18n keys, issue/dimension/
// candidate ids), HTML tags, {placeholders}, markdown-link URLs, numbers, and
// ballot/bill identifiers (Prop 13, AB 259, …) are ASCII and pass through
// OpenCC untouched, so the prose-rendering and citation contracts are preserved.
//
// It rewrites two browser assets in place, between BEGIN/END markers (so re-runs
// replace rather than duplicate):
//   - infra/public/i18n.js          → TRANSLATIONS["zh-Hant"]  (UI chrome)
//   - infra/public/dataset_i18n.js  → DATASET_I18N["zh-Hant"]  (dataset overlay)
//
// Setup: `cd scripts && npm install` (installs opencc-js). Then:
//   node scripts/gen_zh_hant.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import * as OpenCCns from "opencc-js";

const OpenCC = OpenCCns.default || OpenCCns;
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const i18nPath = resolve(root, "infra/public/i18n.js");
const datasetPath = resolve(root, "infra/public/dataset_i18n.js");

const convert = OpenCC.Converter({ from: "cn", to: "tw" });

const BEGIN = "// >>> generated by scripts/gen_zh_hant.mjs — do not edit by hand >>>";
const END = "// <<< end generated zh-Hant <<<";

let stringsConverted = 0;
function deepConvert(value) {
  if (typeof value === "string") {
    stringsConverted++;
    return convert(value);
  }
  if (Array.isArray(value)) return value.map(deepConvert);
  if (value && typeof value === "object") {
    const out = {};
    for (const key of Object.keys(value)) out[key] = deepConvert(value[key]);
    return out;
  }
  return value;
}

// Return the `{ ... }` object-literal text that follows `marker`, matching
// braces while ignoring those inside string literals.
function extractBraced(src, marker) {
  const at = src.indexOf(marker);
  if (at === -1) throw new Error(`marker not found: ${marker}`);
  const start = src.indexOf("{", at);
  let depth = 0, quote = null, escaped = false;
  for (let i = start; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (escaped) escaped = false;
      else if (c === "\\") escaped = true;
      else if (c === quote) quote = null;
    } else if (c === '"' || c === "'" || c === "`") {
      quote = c;
    } else if (c === "{") {
      depth++;
    } else if (c === "}") {
      if (--depth === 0) return src.slice(start, i + 1);
    }
  }
  throw new Error(`unbalanced braces after: ${marker}`);
}

// Return the string-literal text (incl. quotes) assigned at `marker`. Search for
// the opening quote AFTER the marker — the marker itself contains quotes (the
// `["intro.langNote"]` key), so starting from `at` would grab the key, not the value.
function extractString(src, marker) {
  const at = src.indexOf(marker);
  if (at === -1) throw new Error(`marker not found: ${marker}`);
  const start = src.indexOf('"', at + marker.length);
  let escaped = false;
  for (let i = start + 1; i < src.length; i++) {
    const c = src[i];
    if (escaped) escaped = false;
    else if (c === "\\") escaped = true;
    else if (c === '"') return src.slice(start, i + 1);
  }
  throw new Error(`unterminated string after: ${marker}`);
}

const evalLiteral = (text) => new Function(`return (${text});`)();

// Splice a generated block into `src`: replace an existing BEGIN..END region if
// present, else insert at `anchor` (a string to insert before) or append.
function splice(src, block, anchor) {
  const b = src.indexOf(BEGIN);
  if (b !== -1) {
    const e = src.indexOf(END, b);
    if (e === -1) throw new Error("found BEGIN without END");
    return src.slice(0, b) + block + src.slice(e + END.length);
  }
  if (anchor) {
    const at = src.indexOf(anchor);
    if (at === -1) throw new Error(`anchor not found: ${anchor}`);
    return src.slice(0, at) + block + "\n\n" + src.slice(at);
  }
  return src.replace(/\s*$/, "\n") + "\n" + block + "\n";
}

// --- UI chrome: infra/public/i18n.js ------------------------------------------
const i18nSrc = readFileSync(i18nPath, "utf8");
const zhChrome = evalLiteral(extractBraced(i18nSrc, "TRANSLATIONS.zh = {"));
// The langNote is appended as a separate statement after the object; fold it in.
zhChrome["intro.langNote"] = evalLiteral(extractString(i18nSrc, 'TRANSLATIONS.zh["intro.langNote"] = '));
const chromeBlock = `${BEGIN}\nTRANSLATIONS["zh-Hant"] = ${JSON.stringify(deepConvert(zhChrome), null, 2)};\n${END}`;
writeFileSync(i18nPath, splice(i18nSrc, chromeBlock, "(function () {"));

// --- Dataset overlay: infra/public/dataset_i18n.js ----------------------------
// The overlay is built as a main block (questions + dimensions) plus a separate
// `.candidates` assignment appended later; mirror both for zh-Hant.
const datasetSrc = readFileSync(datasetPath, "utf8");
const zhData = evalLiteral(extractBraced(datasetSrc, "DATASET_I18N.zh = {"));
const zhCandidates = evalLiteral(extractBraced(datasetSrc, "DATASET_I18N.zh.candidates = {"));
const dataBlock =
  `${BEGIN}\n` +
  `DATASET_I18N["zh-Hant"] = ${JSON.stringify(deepConvert(zhData), null, 2)};\n` +
  `DATASET_I18N["zh-Hant"].candidates = ${JSON.stringify(deepConvert(zhCandidates), null, 2)};\n` +
  `${END}`;
writeFileSync(datasetPath, splice(datasetSrc, dataBlock));

console.log(`zh-Hant generated: ${stringsConverted} strings converted (cn→tw).`);
console.log("Wrote TRANSLATIONS[\"zh-Hant\"] and DATASET_I18N[\"zh-Hant\"].");
